### ISSUE TITLE
Support for xelatex/lualatex?

### ISSUE THREAD

**Issue by krishnakumarg1984** [fabriziomiano/ThesisTemplate#1]
Can I use custom fonts through xelatex or lualatex?

Also, some showcase of math typography is appreciated.

**Comment by fabriziomiano** [comment]
> Can I use custom fonts through xelatex or lualatex?
I'm not entirely sure, but I don't think you can. It's meant to be compiled with pdflatex

> Also, some showcase of math typography is appreciated.
thanks for pointing this out. Formulas added in Chapter 2
